language: go

go:
  - 1.2

branches:
  only:
  - dev
  
install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get -v github.com/onsi/ginkgo
  - go get -v github.com/onsi/gomega
  - go install -v github.com/onsi/ginkgo/ginkgo


script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --skipMeasurements --cover --trace --race
