language: go

go:
  - 1.1.2

install:
  - go get -v ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go install github.com/onsi/ginkgo/ginkgo

branches:
  only:
  - dev

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --skipMeasurements --cover --trace --race
